name: party_scan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  provider: ^6.1.2
  flutter_barcode_scanner: ^2.0.0
  audioplayers: ^6.0.0
  mobile_scanner: ^5.1.1
  zxing2: ^0.2.3
  shared_preferences: ^2.3.2
  camera: ^0.11.0+2
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/