name: event_scan
description: "An app designed to streamline barcode scanning at events like freshers' parties or Multi Day Programs. Ensures smooth and efficient entry management using Firestore database by checking whether tickets have been scanned before with real-time sync between devices."
publish_to: 'none'
version: 4.1.0+21

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  audioplayers: ^6.0.0
  mobile_scanner: ^7.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_iconpicker: ^4.0.1
  flutter_colorpicker: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^4.0.0
  file_picker: ^10.2.0
  excel: ^4.0.6
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/launcher_icons/
    - assets/sounds/

### flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/launcher_icons/ic_launcher.jpg"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/launcher_icons/ic_launcher_foreground.png"
  adaptive_icon_background: "#b3c9ff"
  remove_alpha_ios: true
  background_color_ios: "#b3c9ff"
  windows:
    generate: true
    image_path: "assets/launcher_icons/icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/launcher_icons/icon-1024x1024.png"