name: Build Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6'

    - name: Write key.properties
      run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

    - name: Write key.jks
      run: echo "${{ secrets.KEY_JKS }}" | base64 --decode > android/key.jks

    - name: Accept Android SDK Licenses
      run: yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build APK
      run: |
        flutter pub get
        dart run flutter_iconpicker:generate_packs --packs material
        flutter build apk --release --split-per-abi --no-tree-shake-icons

    - name: Get version from pubspec.yaml
      id: get_version
      run: |
        VERSION=$(grep '^version: ' pubspec.yaml | sed 's/version: \(.*\)+.*$/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Upload arm64-v8a APK
      uses: actions/upload-artifact@v4
      with:
        name: Event_Scan-v${{ env.VERSION }}-arm64-v8a-release.apk
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

    - name: Upload armeabi-v7a APK
      uses: actions/upload-artifact@v4
      with:
        name: Event_Scan-v${{ env.VERSION }}-armeabi-v7a-release.apk
        path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

    - name: Upload x86_64 APK
      uses: actions/upload-artifact@v4
      with:
        name: Event_Scan-v${{ env.VERSION }}-x86_64-release.apk
        path: build/app/outputs/flutter-apk/app-x86_64-release.apk